#pragma once

enum PipelineType{
    PIPELINE_TYPE_POLYGON,
    PIPELINE_TYPE_CIRCLE,
    PIPELINE_TYPE_OUTLINE,
    PIPELINE_TYPE_COUNT
};

enum RenderPassType{
    RENDER_PASS_TYPE_BASE,
    RENDER_PASS_TYPE_OUTLINE,
    RENDER_PASS_TYPE_IMGUI,
    RENDER_PASS_TYPE_COUNT
};